apiVersion: apps/v1
kind: Deployment

metadata:
  labels:
    app: studio
  name: studio

spec:
  replicas: 1
  selector:
    matchLabels:
      app:  studio
  template:
    metadata:
      labels:
        app: studio
    spec:
      containers:

        - image: gcr.io/joshlong/studio
          imagePullPolicy: Always
          name:  studio

          ports:
            - containerPort: 8080

          env:
            - name: PORT
              value: "8080"


          readinessProbe:
            initialDelaySeconds: 60
            periodSeconds: 60
            httpGet:
              port: 8080
              path: /

          livenessProbe:
            initialDelaySeconds: 60
            periodSeconds: 60
            httpGet:
              port: 8080
              path: /
